DEBUG = True
ALLOWED_FILE_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}
UPLOAD_FOLDER = '/uploads'
HOST = '0.0.0.0'
PORT = 8000
SECRET = 'ASDF!@#$5%$@#$%fasdf'
DEFAULT_RATE = "100/hour"
DATABASE = 'fcc_api.sqlite'
static_url_path='/static'